title: Esoterical's USB Flashing guide
description: A guide for setting up flashing USB Klipper to various hardware on 3D printers
theme: just-the-docs
color_scheme: eso-dark
markdown: kramdown
url: https://usb.esoterical.online
logo: "/assets/esoterical-usb.png"
favicon_ico: "/assets/favicon.ico"

callouts:
  warning:
    title: Warning
    color: red
  stop:
    color: red
  highlight:
    color: yellow

plugins:
  - jekyll-relative-links

aux_links:
  USB Flashing guide on Github: https://github.com/Esoterical/klipper_usb_flashing
